### ISSUE TITLE
Might know why they dont learn

### ISSUE THREAD

**Issue by Epiccoolduse8282** [AqwamCreates/Roblox-Source-Codes#1]
U should make it so it gets rewarded when getting closer tp the enemy, it could also possibly be because of too little reward, i realized that they only attacked eachother when they wrre close to eachother so u can try to maybe change the "in range" and "too close" functions. Keep up the good work, im not planning to steal or anything like that. I kinda just like looking at them learning lol, but ye keep it up bro

**Comment by Epiccoolduse8282** [comment]
U should also add it so they loose reward for looking at the wall even tho if they,re looking at the bot, cause this will maybe make it learn to back into a wall and look at the ai, raither than to attack

**Comment by Epiccoolduse8282** [comment]
The wall reward system should be determined by how close the enemy is

**Comment by Epiccoolduse8282** [comment]
My other plan: looking 90 degrees away from ai = - reward, looking 40 - 30 degrees away from ai = no reward or punishment, looking 30 or less == reward, the less deggrees away from there, the more reward

**Comment by Epiccoolduse8282** [comment]
Let me know what you think of this, reminding you that im just trying to help, and not make my own version or stuff at all.

**Comment by AqwamCreates** [comment]
Unfortunately, as much I like to make changes to those AI sword-fighting AIs, my hands are full on updating the DataPredict library itself. Perhaps you can try those yourself and see how it goes.

**Comment by mellomlia** [comment]
by the way, version 4 doesnt work

**Comment by AqwamCreates** [comment]
Well, if you're talking about the AI keep moving in circles, that's because I have added "ActorModelParameters" module script under the "MainScript". Currently, all AIs will use that model parameters unless you remove "ActorModelParameters" module script. The AI also uses my own custom model instead of usual AdvantageActorCritic model, so feel free to change it.

**Comment by mellomlia** [comment]
no, when i use model 4, it runs for a bit then just stops, idk

søn. 28. apr. 2024 kl. 16:32 skrev Aqwam Harish Aiman <
***@***.***>:

**Comment by mellomlia** [comment]
it says   17:57:57.515  ServerScriptService.MainScript:85: attempt to concatenate Instance with string  -  Server - MainScript:85 now

**Comment by AqwamCreates** [comment]
Try to reupdating it again. I just made some changes to it recently.

**Comment by Epiccoolduse8282** [comment]
They seem to just walk in circles
