### ISSUE TITLE
They keep walking in circles

### ISSUE THREAD

**Issue by mellomlia** [AqwamCreates/Roblox-Source-Codes#2]
Just letting you know, they keep walking in circles cause you removed the circle thingy

**Comment by Epiccoolduse8282** [comment]
What you should do is to make a showcase video on youtube with the version 4

**Comment by Epiccoolduse8282** [comment]
I think ppl would be hyped

**Comment by AqwamCreates** [comment]
@mellomlia , try updating the DataPredictLibrary again. This time, I can see massive change in performance after I added some stuff to Aqwam's Advantage Actor Critic.

**Comment by mellomlia** [comment]
the new rbxl right?, ill try it

**Comment by mellomlia** [comment]
so they seem to just be following eachother in circles

**Comment by mellomlia** [comment]
are they supposed to do that?

**Comment by mellomlia** [comment]
local camping = (isSeeingEnemy and distanceToEnemy >= 10 and -10)

**Comment by mellomlia** [comment]
take a look at this and let me know ur thoughts, its a code that makes it only matter if they look at eachother, if they're close so they wont go to corners and just look at eachother

**Comment by mellomlia** [comment]
so whats ur plan

**Comment by mellomlia** [comment]
alright, do you want me to delete this? im sorry for interupting and i wont missuse the issues again, sorry
