### ISSUE TITLE
how to remove ActorModelParameters 

### ISSUE THREAD

**Issue by mellomlia** [AqwamCreates/Roblox-Source-Codes#4]
im trying to remove ActorModelParameters so they dont run around in circles, but when i do, they run  around for a while but then suddenly just stops, it would mean alot to me if you could explain to me how to

**Comment by mellomlia** [comment]
i remember that you said something about that

**Comment by mellomlia** [comment]
by the way, where do i ask questions? i couldnt answer on the dev forums cause it somehow wouldnt let me chat

**Comment by AqwamCreates** [comment]
Ah, I see. Should have stated that earlier. You can ask questions here then. 

You see the "Labels" section at the right of this comment? Click on that settings icon and choose "Questions". It will mark this as question so that people can filter stuff easily.

**Comment by AqwamCreates** [comment]
Anyways, you can clear the model parameters by calling clearModelParameters() function. Or you can call setModelParameters(nil).

**Comment by mellomlia** [comment]
oh okay, thank you

**Comment by mellomlia** [comment]
hey, it seems like it doesnt work, they keep walking after eachother like they're playing tag
